spring.application.name=resource-server
server.port=8081

# R2DBC ?????? ?? (H2 ????)
spring.r2dbc.url=r2dbc:mysql://localhost:3306/wooricard?useUnicode=true&characterEncoding=utf8

# ?? ?? ??
spring.profiles.active=local
